Fix warnings on lzma.LZMAFile needing a case for Python3 API
Also, Diff-Coverage testing or enforcement in GitHub CI revealed,
a coverage issue which enforced further fixes:

Older tests tested the matrix of .open(filename, {r,w}|{gz,bz2,xz}),
but | is used for passing fileobj, which this test doesn't do.

That led CpioFile.open() to call _Stream which then used _LowLevelFile,
which ment that the gzopen, bz2open and xzopen method calls in dict:OPEN_METH
weren't called, resulting in these functions not getting tested (covered)
by this test.

Updated test_cpio.py to use {r,w}:{gz,bz2,xz} to cover the fixed lines.

This in turn required to fix the dict:OPEN_METH to contain the correct
string to call xzopen for fmt=xz. This means xzopen() was possibly never
tested fully.

This is also suggested by xzopen attempting to call lzma.LZMAFile with
a dict_size of 20

lzma.LZMAFile(name, mode, options={'level': compresslevel, 'dict_size': 20 })

Current pyliblzma versions react to this with:
ValueError: dict_size must be between 4096 and 1610612736, got 20

Because lzma.LZMAFile should know the best dict_size for each level,
the dict_size parameter is no longer attempted to be passed to LZMAFile.

Signed-off-by: Bernhard Kaindl <bernhard.kaindl@cloud.com>