xcp.logger: don't close handlers not owned by us
When run under a test harness that adds its own handler to capture logs,
indiscriminate handler closing after one test causes problems when the
test harness runs several tests in a row.

E.g.:

 Traceback (most recent call last):
   File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit
     stream.write(fs % msg)
 ValueError: I/O operation on closed file
 Logged from file static.py, line 222

Signed-off-by: Yann Dirson <yann.dirson@vates.fr>